# Each route describes how an incoming URL is going to be processed by Platform.sh.
# "https://www.{default}/":
#   type: upstream
#   upstream: "app:http"
# # .platform/routes.yaml
# "https://{default}/":
#     type: upstream
#     upstream: "nodeapp:http"


# "https://{default}/":
#   type: redirect
#   to: "https://www.{default}/"

"https://{default}/":
    type: upstream
    upstream: "nodeapp:http"  # This must match the name in `platform.app.yaml`
    cache:
        enabled: false

"https://{default}/api":
    type: upstream
    upstream: "nodeapp:http"  # Routes to your Node.js app
    cache:
        enabled: false
